### ISSUE TITLE
Ability to split config file

### ISSUE THREAD

**Issue by entity1991** [mskubenich/try_api#2]
Will be cool to give user ability create config yml file per resource, this way .yml file will not so large.

**Comment by mskubenich** [comment]
Good idea !

**Comment by mskubenich** [comment]
https://github.com/mskubenich/try_api/commit/90a66bc97c6fa31b4d86ab1c7a301ae3c961f6a0 - coming soon

**Comment by mskubenich** [comment]
Released in version 0.1.0
